title: Akshay Bhatia
author: akshaybhatia10
email: akshaybhatia10gmail.com
description: > # this means to ignore newlines until "baseurl:"

# social links
github_username:  akshaybhatia10
medium-username:  akshaybhatia10

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
